theme: material
site_name: Super JSS
nav:
  - Home: index.md
  - Installation: installation.md
  - Styling: styling.md
  - Responsive Styling: responsive-style.md
  - Typography: typography.md
  - Theming: theming.md
  - Examples: examples.md

